### ISSUE TITLE
Proposal to add info that testcafe ships with this reporter

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-reporter-json#1]
We have an `Install` section in Readme. I propose to add an info that testcafe ships with this reporter by default, so you don't need to install it separatelly. Otherwise it seems that you need to install it manually
/cc @inikulin @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
Are we talking about the `json` reporter only? If so, why is it different from other reporters shipped with TestCafe? Why is it worth a special notice?

**Comment by AlexanderMoskovkin** [comment]
I mean all built-in reporters. If you read a readme for this plugin you think that you need to install it after you installed testcafe. I had a private question about it from a customer

**Comment by VasilyStrelyaev** [comment]
ah, I see
