### ISSUE TITLE
Report output in .json file

### ISSUE THREAD

**Issue by Singtah** [DevExpress/testcafe-reporter-json#8]
Hi,

I would like to access the JSON result in a JSON file.
Currently, i added the json output file directly in the CLI : 
`"e2e-test": "testcafe firefox test/**/*e2e.ts --reporter json > ./tests/e2e/e2e-test-report.json"`

This is almost perfect but it adds an extra string at the beginning of the json test report :

`Using locally installed version of TestCafe.
{
  "startTime": "2020-10-02T12:50:16.092Z",
  "endTime": "2020-10-02T12:51:25.213Z",
  "userAgents
...
}
`

Is there a way of getting a plain json output ? That would allow the use of the report for data-driven tests

Thank you

**Comment by AlexSkorkin** [comment]
I recommend that you refer to the [-r <name[:output],[...]>, --reporter <name[:output],[...]>](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-r-nameoutput---reporter-nameoutput) topic where this inquiry is described.
